# Run the public T12 examples in an isolated working folder.
# Numerical/scientific interpretation requires additional result checks.
foreach(required_var NXRUNNER RAW_DATA_FILE EXAMPLE_DIR WORK_DIR TEST_BINARY_ROOT)
  if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
    message(FATAL_ERROR "Missing ${required_var}")
  endif()
endforeach()
foreach(required_path "${NXRUNNER}" "${RAW_DATA_FILE}")
  if(NOT EXISTS "${required_path}" OR IS_DIRECTORY "${required_path}")
    message(FATAL_ERROR "Required executable or raw input is missing: ${required_path}")
  endif()
endforeach()

include("${CMAKE_CURRENT_LIST_DIR}/ValidatePipelineCompanion.cmake")
set(pipeline_stems
  "(01) T12 Orientation Preparation"
  "(02) T12 Local and Grain Reference Misorientation")
foreach(stem IN LISTS pipeline_stems)
  validate_companion("${EXAMPLE_DIR}/${stem}.d3dpipeline")
endforeach()

file(MAKE_DIRECTORY "${WORK_DIR}")
file(REAL_PATH "${WORK_DIR}" work_root)
file(REAL_PATH "${TEST_BINARY_ROOT}" test_binary_root)
cmake_path(IS_PREFIX test_binary_root "${work_root}" NORMALIZE work_inside)
if(NOT work_inside OR work_root STREQUAL test_binary_root)
  message(FATAL_ERROR "Test work directory must be below the test binary root: ${work_root}")
endif()
set(raw_stage "${work_root}/Data/T12-MAI-2010")
file(MAKE_DIRECTORY "${raw_stage}")
file(REAL_PATH "${raw_stage}" raw_stage_real)
cmake_path(IS_PREFIX work_root "${raw_stage_real}" NORMALIZE raw_inside)
if(NOT raw_inside)
  message(FATAL_ERROR "Raw staging directory is outside the work directory: ${raw_stage_real}")
endif()
file(COPY_FILE "${RAW_DATA_FILE}" "${raw_stage_real}/fw-ar-IF1-aptr12-corr.ctf" ONLY_IF_DIFFERENT)

foreach(stem IN LISTS pipeline_stems)
  set(pipeline_path "${EXAMPLE_DIR}/${stem}.d3dpipeline")
  file(READ "${EXAMPLE_DIR}/${stem}.yaml" sidecar_json)
  string(JSON output_count LENGTH "${sidecar_json}" outputs)
  if(output_count EQUAL 0)
    message(FATAL_ERROR "Example declares no outputs: ${stem}")
  endif()
  math(EXPR last_output "${output_count} - 1")
  set(expected_outputs "")
  foreach(index RANGE 0 ${last_output})
    string(JSON relative_path GET "${sidecar_json}" outputs ${index} path)
    if(NOT relative_path MATCHES "^Data/Output/T12_Orientation_Examples/" OR relative_path MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "Output must stay within the T12 example output category: ${relative_path}")
    endif()
    set(output_path "${work_root}/${relative_path}")
    get_filename_component(output_parent "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_parent}")
    file(REAL_PATH "${output_parent}" output_parent_real)
    cmake_path(IS_PREFIX work_root "${output_parent_real}" NORMALIZE output_inside)
    if(NOT output_inside OR IS_SYMLINK "${output_path}")
      message(FATAL_ERROR "Unsafe generated output path: ${output_path}")
    endif()
    # Remove only declared products, after checking the resolved parent.
    file(REMOVE "${output_path}")
    if(EXISTS "${output_path}")
      message(FATAL_ERROR "Cannot clear stale output: ${output_path}")
    endif()
    list(APPEND expected_outputs "${output_path}")
  endforeach()
  foreach(mode --preflight --execute)
    string(SUBSTRING "${mode}" 2 -1 mode_name)
    set(log_file "${work_root}/${stem}-${mode_name}.log")
    execute_process(COMMAND "${NXRUNNER}" "${mode}" "${pipeline_path}"
      WORKING_DIRECTORY "${work_root}"
      RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr
      TIMEOUT 600)
    file(WRITE "${log_file}" "Result: ${result}\n${stdout}\n${stderr}\n")
    if(NOT "${result}" STREQUAL "0")
      message(FATAL_ERROR "${stem} ${mode} failed (${result}); see ${log_file}\n${stdout}\n${stderr}")
    endif()
  endforeach()
  foreach(output_path IN LISTS expected_outputs)
    if(NOT EXISTS "${output_path}" OR IS_DIRECTORY "${output_path}")
      message(FATAL_ERROR "Execution did not create the declared output: ${output_path}")
    endif()
    file(SIZE "${output_path}" output_size)
    if(output_size EQUAL 0)
      message(FATAL_ERROR "Execution created an empty output: ${output_path}")
    endif()
  endforeach()
endforeach()
