# Run the consolidated orientation case study from the public CTF input.
include("${CMAKE_CURRENT_LIST_DIR}/../../../../cmake/RunExamplePipelineChain.cmake")
foreach(required_var NXRUNNER RAW_DATA_FILE EXAMPLE_DIR WORK_DIR TEST_BINARY_ROOT)
  if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
    message(FATAL_ERROR "Missing ${required_var}")
  endif()
endforeach()
foreach(required_path "${NXRUNNER}" "${RAW_DATA_FILE}")
  if(NOT EXISTS "${required_path}" OR IS_DIRECTORY "${required_path}")
    message(FATAL_ERROR "Required executable or raw input is missing: ${required_path}")
  endif()
endforeach()
set(OUTPUT_CATEGORY "T12_Orientation_Examples")
set(pipeline_stems "(01) T12 Orientation Case Study")
validate_companion("${EXAMPLE_DIR}/${pipeline_stems}.d3dpipeline")
prepare_example_workspace()
file(REAL_PATH "${WORK_DIR}" work_root)
set(raw_stage "${work_root}/Data/T12-MAI-2010")
file(MAKE_DIRECTORY "${raw_stage}")
file(REAL_PATH "${raw_stage}" raw_stage_real)
cmake_path(IS_PREFIX work_root "${raw_stage_real}" NORMALIZE raw_inside)
if(NOT raw_inside)
  message(FATAL_ERROR "Raw staging directory is outside the work directory: ${raw_stage_real}")
endif()
set(staged_ctf "${raw_stage_real}/fw-ar-IF1-aptr12-corr.ctf")
if(IS_SYMLINK "${staged_ctf}")
  message(FATAL_ERROR "Raw staging file must not be a symbolic link: ${staged_ctf}")
endif()
file(COPY_FILE "${RAW_DATA_FILE}" "${staged_ctf}" ONLY_IF_DIFFERENT)
run_example_pipeline_chain()
