include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ValidatePipelineCompanion.cmake")

function(prepare_example_workspace)
  foreach(required_var NXRUNNER WORK_DIR TEST_BINARY_ROOT)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
      message(FATAL_ERROR "Missing ${required_var}")
    endif()
  endforeach()
  file(MAKE_DIRECTORY "${WORK_DIR}")
  file(REAL_PATH "${WORK_DIR}" resolved_work)
  file(REAL_PATH "${TEST_BINARY_ROOT}" resolved_binary_root)
  cmake_path(IS_PREFIX resolved_binary_root "${resolved_work}" NORMALIZE work_inside)
  if(NOT work_inside OR resolved_work STREQUAL resolved_binary_root)
    message(FATAL_ERROR "Example work directory must be below its binary root: ${resolved_work}")
  endif()
endfunction()

# Run a declared predecessor in the same isolated work directory.
function(run_example_prerequisite stage script example_dir)
  prepare_example_workspace()
  if(NOT stage MATCHES "^[A-Za-z0-9_]+$")
    message(FATAL_ERROR "Invalid predecessor stage: ${stage}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DNXRUNNER=${NXRUNNER}" "-DEXAMPLE_DIR=${example_dir}"
    "-DWORK_DIR=${WORK_DIR}" "-DTEST_BINARY_ROOT=${TEST_BINARY_ROOT}"
    ${ARGN} -P "${script}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 1500)
  file(WRITE "${WORK_DIR}/${stage}-prerequisite.log" "Result: ${result}\n${stdout}\n${stderr}\n")
  if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Predecessor ${stage} failed (${result}): ${WORK_DIR}/${stage}-prerequisite.log\n${stdout}\n${stderr}")
  endif()
endfunction()

function(run_example_pipeline_chain)
  foreach(required_var NXRUNNER EXAMPLE_DIR WORK_DIR TEST_BINARY_ROOT OUTPUT_CATEGORY pipeline_stems)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
      message(FATAL_ERROR "Missing ${required_var}")
    endif()
  endforeach()
  if(NOT OUTPUT_CATEGORY MATCHES "^[A-Za-z0-9_]+$")
    message(FATAL_ERROR "Invalid output category: ${OUTPUT_CATEGORY}")
  endif()
  foreach(stem IN LISTS pipeline_stems)
    validate_companion("${EXAMPLE_DIR}/${stem}.d3dpipeline")
  endforeach()
  file(MAKE_DIRECTORY "${WORK_DIR}")
  file(REAL_PATH "${WORK_DIR}" work_root)
  file(REAL_PATH "${TEST_BINARY_ROOT}" test_binary_root)
  cmake_path(IS_PREFIX test_binary_root "${work_root}" NORMALIZE work_inside)
  if(NOT work_inside OR work_root STREQUAL test_binary_root)
    message(FATAL_ERROR "Test work directory must be below the test binary root: ${work_root}")
  endif()
  set(category_root "${work_root}/Data/Output/${OUTPUT_CATEGORY}")
  foreach(stem IN LISTS pipeline_stems)
    set(pipeline_path "${EXAMPLE_DIR}/${stem}.d3dpipeline")
    file(READ "${EXAMPLE_DIR}/${stem}.yaml" sidecar_json)
    string(JSON output_count LENGTH "${sidecar_json}" outputs)
    if(output_count EQUAL 0)
      message(FATAL_ERROR "Example declares no outputs: ${stem}")
    endif()
    math(EXPR last_output "${output_count} - 1")
    set(expected_outputs "")
    foreach(index RANGE 0 ${last_output})
      string(JSON relative_path GET "${sidecar_json}" outputs ${index} path)
      string(FIND "${relative_path}" "\\" backslash_index)
      if(NOT relative_path MATCHES "^Data/Output/${OUTPUT_CATEGORY}/" OR relative_path MATCHES "(^|/)\\.\\.(/|$)" OR NOT backslash_index EQUAL -1)
        message(FATAL_ERROR "Output must stay within the declared example output category: ${relative_path}")
      endif()
      set(output_path "${work_root}/${relative_path}")
      get_filename_component(output_parent "${output_path}" DIRECTORY)
      file(MAKE_DIRECTORY "${output_parent}")
      file(REAL_PATH "${output_parent}" output_parent_real)
      cmake_path(IS_PREFIX category_root "${output_parent_real}" NORMALIZE output_inside)
      if(NOT output_inside OR IS_SYMLINK "${output_path}")
        message(FATAL_ERROR "Unsafe generated output path: ${output_path}")
      endif()
      # Remove only declared products, after checking the resolved parent.
      file(REMOVE "${output_path}")
      if(EXISTS "${output_path}")
        message(FATAL_ERROR "Cannot clear stale output: ${output_path}")
      endif()
      list(APPEND expected_outputs "${output_path}")
    endforeach()
    foreach(mode --preflight --execute)
      string(SUBSTRING "${mode}" 2 -1 mode_name)
      set(log_file "${work_root}/${stem}-${mode_name}.log")
      execute_process(COMMAND "${NXRUNNER}" "${mode}" "${pipeline_path}"
        WORKING_DIRECTORY "${work_root}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr
        TIMEOUT 600)
      file(WRITE "${log_file}" "Result: ${result}\n${stdout}\n${stderr}\n")
      if(NOT "${result}" STREQUAL "0")
        message(FATAL_ERROR "${stem} ${mode} failed (${result}); see ${log_file}\n${stdout}\n${stderr}")
      endif()
    endforeach()
    foreach(output_path IN LISTS expected_outputs)
      if(NOT EXISTS "${output_path}" OR IS_DIRECTORY "${output_path}")
        message(FATAL_ERROR "Execution did not create the declared output: ${output_path}")
      endif()
      file(SIZE "${output_path}" output_size)
      if(output_size EQUAL 0)
        message(FATAL_ERROR "Execution created an empty output: ${output_path}")
      endif()
    endforeach()
  endforeach()

endfunction()
