include_guard(GLOBAL)

# Keep each human/AI companion aligned with its executable pipeline. The YAML
# files use JSON syntax, so CMake can inspect them without a Python dependency.
function(validate_companion pipeline_path)
  get_filename_component(pipeline_stem "${pipeline_path}" NAME_WE)
  get_filename_component(pipeline_filename "${pipeline_path}" NAME)
  get_filename_component(pipeline_dir "${pipeline_path}" DIRECTORY)
  set(sidecar_path "${pipeline_dir}/${pipeline_stem}.yaml")
  set(companion_path "${pipeline_dir}/${pipeline_stem}.md")
  get_filename_component(companion_filename "${companion_path}" NAME)
  if(NOT EXISTS "${sidecar_path}")
    message(FATAL_ERROR "Missing sidecar for ${pipeline_path}: ${sidecar_path}")
  endif()
  if(NOT EXISTS "${companion_path}")
    message(FATAL_ERROR "Missing Markdown companion for ${pipeline_path}: ${companion_path}")
  endif()
  file(READ "${pipeline_path}" pipeline_json)
  file(READ "${sidecar_path}" sidecar_json)
  file(READ "${companion_path}" companion_text)
  string(FIND "${companion_text}" "**Before adapting:**" adaptation_notice)
  string(FIND "${companion_text}" "## At a glance" glance_heading)
  string(FIND "${companion_text}" "## Purpose and real-world setting" purpose_heading)
  string(FIND "${companion_text}" "${pipeline_stem}.d3dpipeline" executable_name)
  if(adaptation_notice LESS 0 OR glance_heading LESS 0 OR purpose_heading LESS 0 OR executable_name LESS 0)
    message(FATAL_ERROR "Markdown adaptation notice, At a glance, purpose heading, or executable name is missing: ${companion_path}")
  endif()
  if(executable_name GREATER adaptation_notice OR adaptation_notice GREATER glance_heading OR glance_heading GREATER purpose_heading)
    message(FATAL_ERROR "Markdown executable name, adaptation notice, At a glance, and purpose heading are out of order: ${companion_path}")
  endif()
  string(JSON step_count ERROR_VARIABLE pipeline_error LENGTH "${pipeline_json}" pipeline)
  string(JSON sidecar_step_count ERROR_VARIABLE sidecar_error LENGTH "${sidecar_json}" steps)
  if(NOT pipeline_error STREQUAL "NOTFOUND" OR NOT sidecar_error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "Invalid pipeline or sidecar JSON: ${pipeline_path}, ${sidecar_path}")
  endif()
  string(JSON sidecar_pipeline_file ERROR_VARIABLE pipeline_file_error GET "${sidecar_json}" pipeline_file)
  string(JSON sidecar_markdown_file ERROR_VARIABLE markdown_file_error GET "${sidecar_json}" markdown_file)
  if(NOT pipeline_file_error STREQUAL "NOTFOUND" OR NOT sidecar_pipeline_file STREQUAL pipeline_filename)
    message(FATAL_ERROR "pipeline_file must match ${pipeline_filename}: ${sidecar_path}")
  endif()
  if(NOT markdown_file_error STREQUAL "NOTFOUND" OR NOT sidecar_markdown_file STREQUAL companion_filename)
    message(FATAL_ERROR "markdown_file must match ${companion_filename}: ${sidecar_path}")
  endif()
  if(NOT step_count EQUAL sidecar_step_count)
    message(FATAL_ERROR "Step count differs: ${pipeline_path} has ${step_count}, ${sidecar_path} has ${sidecar_step_count}")
  endif()

  math(EXPR last_step "${step_count} - 1")
  foreach(step RANGE 0 ${last_step})
    string(JSON sidecar_index GET "${sidecar_json}" steps ${step} index)
    string(JSON pipeline_uuid GET "${pipeline_json}" pipeline ${step} filter uuid)
    string(JSON sidecar_uuid GET "${sidecar_json}" steps ${step} uuid)
    string(JSON full_filter_name GET "${pipeline_json}" pipeline ${step} filter name)
    string(REGEX REPLACE "^.*::" "" filter_class "${full_filter_name}")
    string(JSON sidecar_filter GET "${sidecar_json}" steps ${step} filter)
    if(NOT sidecar_index EQUAL step OR NOT pipeline_uuid STREQUAL sidecar_uuid OR NOT filter_class STREQUAL sidecar_filter)
      message(FATAL_ERROR "Step ${step} index/filter/UUID mismatch in ${pipeline_path} and ${sidecar_path}")
    endif()

    string(JSON pipeline_param_version GET "${pipeline_json}" pipeline ${step} args parameters_version)
    string(JSON sidecar_param_version GET "${sidecar_json}" steps ${step} parameters_version)
    if(NOT pipeline_param_version STREQUAL sidecar_param_version)
      message(FATAL_ERROR "Step ${step} parameters_version mismatch in ${pipeline_path} and ${sidecar_path}")
    endif()

    string(JSON arg_count LENGTH "${pipeline_json}" pipeline ${step} args)
    string(JSON key_count LENGTH "${sidecar_json}" steps ${step} key_parameters)
    math(EXPR expected_key_count "${arg_count} - 1")
    if(NOT key_count EQUAL expected_key_count)
      message(FATAL_ERROR "Step ${step} parameter-key count mismatch in ${pipeline_path} and ${sidecar_path}")
    endif()
    math(EXPR last_arg "${arg_count} - 1")
    foreach(arg RANGE 0 ${last_arg})
      string(JSON key MEMBER "${pipeline_json}" pipeline ${step} args ${arg})
      if(key STREQUAL "parameters_version")
        continue()
      endif()
      string(JSON source_type TYPE "${pipeline_json}" pipeline ${step} args "${key}" value)
      string(JSON sidecar_type ERROR_VARIABLE key_error TYPE "${sidecar_json}" steps ${step} key_parameters "${key}")
      if(NOT key_error STREQUAL "NOTFOUND" OR NOT source_type STREQUAL sidecar_type)
        message(FATAL_ERROR "Step ${step} parameter ${key} type/missing-key mismatch in ${pipeline_path} and ${sidecar_path}")
      endif()
      string(JSON source_value GET "${pipeline_json}" pipeline ${step} args "${key}" value)
      string(JSON sidecar_value GET "${sidecar_json}" steps ${step} key_parameters "${key}")
      if(source_type STREQUAL "OBJECT" OR source_type STREQUAL "ARRAY")
        string(JSON values_equal EQUAL "${source_value}" "${sidecar_value}")
      elseif("${source_value}" STREQUAL "${sidecar_value}")
        set(values_equal TRUE)
      else()
        set(values_equal FALSE)
      endif()
      if(NOT values_equal)
        message(FATAL_ERROR "Step ${step} parameter ${key} value mismatch in ${pipeline_path} and ${sidecar_path}")
      endif()
    endforeach()
  endforeach()
endfunction()
