include("${CMAKE_CURRENT_LIST_DIR}/../../../../cmake/RunExamplePipelineChain.cmake")
set(OUTPUT_CATEGORY "Bentheimer_Resolution_Examples")
set(pipeline_stems
  "(01) Bentheimer Native Volume Preparation"
  "(02) Bentheimer Common Grid Comparison"
  "(03) Bentheimer Interior Region Comparison"
)
foreach(stem IN LISTS pipeline_stems)
  validate_companion("${EXAMPLE_DIR}/${stem}.d3dpipeline")
endforeach()
prepare_example_workspace()
file(REAL_PATH "${WORK_DIR}" work_root)
set(data_dir "${work_root}/Data/${OUTPUT_CATEGORY}")
file(MAKE_DIRECTORY "${data_dir}")
file(REAL_PATH "${data_dir}" resolved_data_dir)
cmake_path(IS_PREFIX work_root "${resolved_data_dir}" NORMALIZE data_inside)
if(NOT data_inside)
  message(FATAL_ERROR "Input staging directory must stay in the test workspace: ${resolved_data_dir}")
endif()

# Inputs are small published volumes; use the application cache when available.
get_filename_component(runtime_dir "${NXRUNNER}" DIRECTORY)
file(READ "${EXAMPLE_DIR}/DataSources.json" sources)
string(JSON file_count LENGTH "${sources}" files)
if(NOT file_count EQUAL 2)
  message(FATAL_ERROR "Expected the two declared Bentheimer input volumes")
endif()
foreach(index RANGE 0 1)
  string(JSON filename GET "${sources}" files ${index} filename)
  string(JSON url GET "${sources}" files ${index} url)
  string(JSON expected_hash GET "${sources}" files ${index} sha512)
  if(NOT filename MATCHES "^[A-Za-z0-9_.-]+[.]raw$" OR filename MATCHES "[.][.]")
    message(FATAL_ERROR "Invalid input filename: ${filename}")
  endif()
  set(input_path "${resolved_data_dir}/${filename}")
  set(cache_path "${runtime_dir}/Data/${OUTPUT_CATEGORY}/${filename}")
  if(IS_SYMLINK "${input_path}")
    message(FATAL_ERROR "Input staging path must not be a symbolic link: ${input_path}")
  endif()
  if(EXISTS "${input_path}")
    file(SHA512 "${input_path}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
      message(FATAL_ERROR "Staged input checksum mismatch: ${input_path}")
    endif()
  elseif(EXISTS "${cache_path}")
    file(SHA512 "${cache_path}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
      message(FATAL_ERROR "Cached input checksum mismatch: ${cache_path}")
    endif()
    file(COPY_FILE "${cache_path}" "${input_path}")
  else()
    set(download_path "${input_path}.download")
    if(IS_SYMLINK "${download_path}" OR IS_DIRECTORY "${download_path}")
      message(FATAL_ERROR "Unsafe temporary input path: ${download_path}")
    endif()
    file(DOWNLOAD "${url}" "${download_path}"
      EXPECTED_HASH "SHA512=${expected_hash}" TLS_VERIFY ON TIMEOUT 300)
    file(RENAME "${download_path}" "${input_path}")
  endif()
endforeach()
run_example_pipeline_chain()
